version: 2.0
references:
  - &container_config
    docker:
      - image: circleci/node:10-browsers
        environment:
          JOBS: 2
    working_directory: ~/ember-cli-crowdin

  - &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

  - &restore_node_modules
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        - v1-dependencies

  - &npm_rc
    run:
      name: Add npmrc file
      command: |
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

  - &known_hosts
    run:
      name: Add npmrc file
      command: |
        ssh-keyscan github.com >> ~/.ssh/known_hosts

  - &git_config
    run:
      name: Add git config
      command: |
        git config user.email "$BOT_GH_EMAIL" > /dev/null 2>&1
        git config user.name "$BOT_GH_NAME" > /dev/null 2>&1

jobs:
  checkout_code:
    <<: *container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
      - *npm_rc
      - *git_config
      - *known_hosts
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  deploy_master:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - *npm_rc
      - *git_config
      - run: mkdir ~/.ssh
      - *known_hosts
      - run:
          name: Deploy Master CI
          command: yarn deploy:ci
      - run:
          name: NPM PUBLISH
          command: npm publish

  lint:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - run: yarn lint:js

  test-release:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - *npm_rc
      - run: node_modules/.bin/ember try:one ember-release --skip-cleanup --reporter=dot

  test-beta:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - *npm_rc
      - run: node_modules/.bin/ember try:one ember-beta --skip-cleanup --reporter=dot

  test-canary:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - *npm_rc
      - run: node_modules/.bin/ember try:one ember-canary --skip-cleanup --reporter=dot

  test-default:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - *npm_rc
      - run: yarn test

workflows:
  version: 2

  must_pass:
    jobs:
      - checkout_code

      - lint:
          requires:
            - checkout_code

      - test-default:
          requires:
            - lint

      - test-release:
          requires:
            - lint

      - deploy_master:
          requires:
            - test-default
          filters:
            branches:
              only: master

  can_fail:
    jobs:
      - checkout_code

      - lint:
          requires:
            - checkout_code

      - test-beta:
          requires:
            - lint
